spring.application.name=VideoRent

spring.datasource.url=jdbc:postgresql://localhost:5432/webdb
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
